### ISSUE TITLE
请支持 SSR 模式引入

### ISSUE THREAD

**Issue by liiil825** [TencentCloudBase/cloudbase-vue#16]

**Comment by chhpt** [comment]
cloudbase-vue 已支持在 SSR Client 模式下引入

**Comment by liiil825** [comment]
Client模式是ssr吗？这句话的意思等同于，我支持ssr，但要在ssr模式下关闭使用ssr

**Comment by chhpt** [comment]
@liiil825 SSR 不是只有 Server 端，也有 Client 端，cloudbase-vue 仅支持在 Client 端运行，不支持也没有计划支持在 Server 端运行。

在 SSR Server 端请使用 @cloudbase/node-sdk。

**Comment by liiil825** [comment]
ssr = server-side rendering
直说不支持不就完了？

**Comment by chhpt** [comment]
@liiil825 按照你对 SSR 这样的理解，可以说不支持
