### ISSUE TITLE
js文件里怎么调用

### ISSUE THREAD

**Issue by Erik-Wong** [TencentCloudBase/cloudbase-vue#3]

**Comment by chhpt** [comment]
@Erik-Wong  README  中有说明的

**Comment by lithiumhydride** [comment]
> @Erik-Wong README 中有说明的

只能在vue组件中调用this.$cloudbase吗？

**Comment by lithiumhydride** [comment]
> @Erik-Wong README 中有说明的

请问只能在Vue组件中调用this.$cloudbase吗？能否像tcb-js-sdk那样在js文件中单独调用呢？

**Comment by DaZiYuan** [comment]
我也想问，在非vue组件中，如何获取tcb实例？

**Comment by liiil825** [comment]
确实有这样的问题，如果用 `composition-api` 是无法访问 this 的

**Comment by chhpt** [comment]
如果不能使用 this，可以直接使用 @cloudbase/js-sdk。这只是 Vue 的一个插件，你任然可以在 Vue 中使用 @cloudbase/js-sdk。

**Comment by DaZiYuan** [comment]
同时用2个sdk，要初始化两次，所以我果断选择了cloudbase/js-sdk
